#Feature Engineering

##Assignment

**Question. No. 1. What is a parameter?**

**Answer.** In statistics and machine learning, a parameter is a value that characterizes a model or population. For example, in a linear regression model y=mx+c, both m (slope) and c (intercept) are parameters that define the line's shape. In machine learning, parameters are learned from data during training. These include weights in neural networks or coefficients in regression, which help the model make accurate predictions.

**Question. No. 2. What is correlation? What does negative correlation  mean?**

**Answer.** Correlation measures the strength and direction of a linear relationship between two variables. It ranges from -1 to +1. A value near +1 indicates a strong positive relationship, where both variables increase together. A negative correlation (value close to -1) means that as one variable increases, the other decreases. For example, the number of hours a person spends watching TV may be negatively correlated with academic performance—more TV might mean lower grades.For example, as outdoor temperature rises, heating expenses typicaly fall.

**Question. No. 3. Define Machine Learning. What are the main components in Machine Learning?**

**Answer.** Machine learning is a subfield of artificial intelligence that enables computers to learn patterns from data and make decisions or predictions without being explicitly programmed. The main components of machine learning are:

**Model** - a mathematical structure used to make predictions.

**Loss Function** - a way to measure how good the model is.

**Optimizer** - adjusts model parameters to reduce error.

**Data** - labeled or unlabeled examples that the model learns from.        vjkgk

**Question. No. 4. How does loss value help in determining whether the model is good or not?**

**Answer.** The loss value is a measure of how far off a model's predictions are from the actual results. A lower loss indicates that the model is making accurate predictions. It helps during training by guiding the optimizer on how to adjust parameters to improve the model. However, a very low loss on training data can sometimes indicate overfitting, where the model performs well on known data but poorly on new, unseen data.

**Question. No. 5. What are continuous and categorical variables?**

**Answer.** Continuous variables are numerical and can take an infinite number of values within a range, such as height, weight, or temperature. They are measurable quantities. Categorical variables represent distinct categories or groups and are not inherently numerical. Examples include gender, country, or type of product. In machine learning, it’s important to treat them differently—for instance, continuous variables might be scaled, while categorical variables are encoded into numerical format.

**Question. No. 6. How do we handle categorical variable in Machine Learning? What are the common techniques?**

**Answer.** Categorical variables must be converted into a numerical form before being used in most machine learning models. Common techniques include Label Encoding, where each category is assigned a unique integer (e.g., Male = 0, Female = 1), and One-Hot Encoding, which creates binary columns for each category. Another method is Target Encoding, where categories are replaced with their average target value. Choosing the right encoding depends on the type of data and the algorithm used.

**Question. No. 7. What do you mean by training and testing a dataset?**

**Answer.** Training a dataset involves feeding a machine learning model with input features and known outcomes so it can learn patterns. Testing a dataset means using new, unseen data to evaluate the model’s performance. Splitting the dataset ensures that the model doesn’t just memorize the training data but can also generalize to new inputs. This practice helps detect overfitting and validates how well the model might perform in real-world scenarios.


**Question. No. 8. What is sklearn.preprocessing?**

**Answer.** sklearn.preprocessing is a module in the scikit-learn library that contains tools for preparing data before model training. It includes methods for feature scaling (like StandardScaler, MinMaxScaler), normalization, encoding categorical variables (like OneHotEncoder, LabelEncoder), and more. Preprocessing ensures that features are on a similar scale and in a suitable format for the learning algorithms, improving training speed and accuracy.

**Question. No. 9. What is a Test set?**

**Answer.** A test set is a separate portion of the dataset reserved to evaluate the trained model’s performance. It is not used during the training phase, which helps in assessing how well the model generalizes to unseen data. For example, in a typical 80/20 split, 80% of the data is used for training, while 20% is used for testing. A good model should perform well on both training and test sets to be considered robust.

**Question. No. 10. How do we split data for model fitting (training and testing) in Python? How do you approach a Machine Learning problem?**

**Answer.** In Python, we commonly use train_test_split() from sklearn.model_selection to divide the dataset. A typical split is 70–80% for training and 20–30% for testing. To approach a machine learning problem:

1. Understand the problem and data.

2. Perform EDA (exploratory data analysis).

3. Preprocess the data (handle missing values, scale, encode).

4. Split the data.

5. Choose and train a model.

6. Evaluate the model.

7. Fine-tune and deploy.

**Question. No. 11. Why do we have to perform EDA before fitting a model to the data?**

**Answer.** EDA, or Exploratory Data Analysis, is crucial for understanding the data’s structure, patterns, and anomalies. It helps identify missing values, outliers, feature distributions, and relationships between variables. By performing EDA, you can make informed decisions on preprocessing, feature selection, or engineering. It also reveals whether your assumptions about the data hold, which directly affects model performance. Skipping EDA can lead to incorrect models due to unseen data issues.

**Question. No. 12. What is correlation?**

**Answer.** Correlation is a statistical measure that describes the degree to which two variables move in relation to each other. It ranges from -1 to +1. A correlation of +1 means both variables increase together perfectly, while -1 means one increases as the other decreases. A correlation of 0 means no linear relationship. It’s widely used in data analysis and machine learning to detect dependencies between variables and guide feature selection.

**Question. No. 13. What does negative correlation mean?**

**Answer.** Negative correlation means that as one variable increases, the other decreases. For example, if hours spent watching TV increase, academic performance might decline—this shows an inverse relationship. In mathematical terms, negative correlation values range between 0 and -1. A value of -1 means a perfect negative correlation. This insight helps in understanding which features might be inversely affecting the target variable in a model.

**Question. No. 14. How can you find correlation between variables in Python?**

**Answer.** In Python, correlation can be computed using pandas.DataFrame.corr(), which returns a correlation matrix using Pearson's method by default. You can also use scipy.stats.pearsonr() for more detailed output. To visualize correlation, the seaborn library’s heatmap() is commonly used, which displays a color-coded matrix showing how strongly each variable relates to the others. This helps in selecting important features and avoiding multicollinearity.

**Question. No. 15. What is causation? Explain difference between correlation and causation with an example.**

**Answer.** Causation implies a direct cause-and-effect relationship between two variables, whereas correlation simply shows they are related. For example, increased ice cream sales correlate with higher drowning incidents, but ice cream does not cause drowning. The real cause might be summer (a lurking variable). In machine learning and statistics, it's essential not to confuse correlation with causation, as it can lead to incorrect assumptions and decisions in analysis and model design.

**Question. No. 16. What is Optimizer? What are different types of optimizers? Explain each with an example.**

**Answer.** An optimizer is an algorithm used during model training to adjust parameters like weights and biases to minimize the loss function. Common optimizers include:

**Gradient Descent**: Updates parameters using the full dataset.

**Stochastic Gradient Descent (SGD)**: Updates parameters using one data point at a time, faster but noisier.

**Adam:** Combines momentum and adaptive learning rate, widely used for deep learning.
For example, Adam is often used in training neural networks for its efficiency and speed.

**Question. No. 17. What is sklearn.linear_model?**

**Answer.** sklearn.linear_model is a module in the Scikit-learn library that provides linear models for regression and classification. Some key classes include LinearRegression for predicting continuous values, LogisticRegression for binary classification, and Ridge and Lasso for regularized regression. These models are simple yet powerful, easy to interpret, and often serve as a good starting point for many machine learning tasks, especially when relationships between variables are linear.

**Question. No. 18. What does model.fit() do? What arguments must be given?**

**Answer.** The model.fit() function trains the model on the given data. It takes two primary arguments: X (features/input variables) and y (target/output variable). During this process, the model learns the patterns and relationships in the data by adjusting its internal parameters. Some models may accept additional arguments such as epochs, batch_size, or validation_data depending on the algorithm and library used (especially in deep learning frameworks like Keras).

**Question. No. 19. What does model.predict() do? What arguments must be given?**

**Answer.** The model.predict() function is used after training to make predictions on new or unseen data. The only required argument is X_new, which is the new input data for which we want to make predictions. The function outputs predicted values in the same format as the target variable. For example, if you're predicting house prices, model.predict(X_test) will return the predicted prices for the test dataset.

**Question. No. 20. What are continuous and categorical variables?**

**Answer.** Continuous variables are numeric variables that can take an infinite number of values within a range, like temperature, height, or salary. They are measurable and often used in regression problems. Categorical variables represent discrete groups or classes, such as gender, color, or education level. These can be nominal (no order) or ordinal (with order). Proper handling of both types is essential during preprocessing for accurate machine learning model performance.

**Question. No. 21. What is feature scaling? How does it help in Machine Learning?**

**Answer.** Feature scaling is the process of normalizing or standardizing the range of independent variables or features. It ensures that no feature dominates others due to differing units or scales. For example, age (0–100) and salary (in lakhs) need to be scaled for algorithms like KNN or SVM to function properly. Common scaling methods include Min-Max scaling (0 to 1) and Standardization (mean = 0, std = 1). It speeds up training and improves model accuracy.

**Question. No. 22. How do we perform scaling in Python?**

**Answer.** In Python, we can use the sklearn.preprocessing module for scaling. The two most commonly used classes are:

**StandardScaler:** Scales data to have a mean of 0 and standard deviation of 1.

**MinMaxScaler:** Scales features to a specific range, usually [0,1].
Usage example:


In [2]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample data (replace with your actual data)
X = np.array([[1, 2], [3, 4], [5, 6]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Original data:\n", X)
print("\nScaled data:\n", X_scaled)

Original data:
 [[1 2]
 [3 4]
 [5 6]]

Scaled data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


These tools help ensure balanced input for the model.

**Question. No. 23. What is sklearn.preprocessing?**

**Answer.** sklearn.preprocessing is a module in the Scikit-learn library that provides tools for transforming and preparing raw data before modeling. It includes techniques for:

**Scaling** (StandardScaler, MinMaxScaler)

**Encoding categorical variables** (LabelEncoder, OneHotEncoder)

**Binarizing features**

**Polynomial feature generation**, and more.
Proper preprocessing with this module ensures better learning efficiency, faster convergence, and improved model performance, especially with algorithms sensitive to feature distributions.

**Question. No. 24. How do we split data for model fitting (training and testing) in Python?**

**Answer.** We use train_test_split() from sklearn.model_selection to divide the dataset into training and testing sets. A common split is 70% training and 30% testing. Example:


In [4]:
from sklearn.model_selection import train_test_split
import numpy as np

# Sample data (replace with your actual data)
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) # Sample target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Original X data:\n", X)
print("\nOriginal y data:\n", y)
print("\nX_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Original X data:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

Original y data:
 [0 1 0 1 0 1 0 1 0 1]

X_train shape: (7, 2)
X_test shape: (3, 2)
y_train shape: (7,)
y_test shape: (3,)


This method helps evaluate how well a model generalizes to new data and is a critical step in the machine learning pipeline.

**Question. No. 25. Explain data encoding?**

**Answer.** Data encoding transforms categorical values into a numerical format suitable for machine learning algorithms. This is necessary because most models require numeric input. Techniques include:

**Label Encoding:** Assigns an integer to each category.

**One-Hot Encoding:** Converts categories into binary vectors.

**Target Encoding:** Replaces categories with average target values.
Proper encoding prevents misleading the model with ordinal relationships where none exist and ensures better training performance.

